name: platformx
description: Lightweight platform checking utility for Flutter. Works for all platforms.
homepage: https://github.com/adrianflutur/platformx
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
